#!/usr/bin/env bash

ansible-playbook -v /etc/ansible/jdk.yml
ansible-playbook -v zk.yml
ansible-playbook -v -e first_install=true hadoop.yml
ansible-playbook -v -e first_install=true hive.yml
ansible-playbook -v spark.yml